// Simple Camera has a 90 degree field of view along the z axis.
#ifndef _SIMPLE_CAMERA_H_
#define _SIMPLE_CAMERA_H_

#include "camera.h"

class SimpleCamera : public Camera {
 public:
  float width;
  float height;
  float fov;

  SimpleCamera();

  SimpleCamera(float p_f);

  void get_ray_pixel(int p_x, int p_y, Ray& p_ray);

  // Given an Environment, call env.raytrace() on each of the rays generated by
  // get_ray_pixel and store the result in the framebuffer
  void render(Environment& env, FrameBuffer& fb);
};

#endif
